### ISSUE TITLE
Video stops after a short period or doesn't play at all

### ISSUE THREAD

**Issue by Aldrog** [Aldrog/TwitchTube#2]
Here you can leave a log if this bug affects you.

**Comment by raikirii** [comment]
Hey, it's me again.

Two twitch logs:
http://pastebin.com/0fdXF0CM
http://pastebin.com/95YSnxeA

Both times the video recovered 2 times. When it recovered the second time it stopped and the video stood still. chat worked. In general when I try to watch with TwitchTube I can watch for about 5 to 15 seconds, then the video stops, recovers, video works for 5 to 15 seconds, and so on. Eventually the video "freezes" and I have to go back to the stream catalog and restart the stream from there.

zypper:
http://pastebin.com/ZDRXHSAH

toggle text wrapping on the zypperlog for reading

**Comment by Aldrog** [comment]
It seems like there're 3 different video issues: stopping and resuming every few seconds (actually issue #1), some sort of decoding error and "freezing" of the video after a while.

**Comment by Termitebug** [comment]
Hi, I have no playback at all and it is repeatable. My version is 0.2.1-2.

My logs;
app:
https://www.asuswebstorage.com/navigate/s/BC5FF5C4C26D46DC8D0273A458DC14134
zypper:
https://www.asuswebstorage.com/navigate/s/D94E3F0044AA425EAA83CE6CF1EC4EF24

In my case video or audio doesn't start at all. App shows only "freezed snapshot" of stream when applying different quality settings. Otherwise the stream is always *Chat only. Chat and login are only features which works for me.

**Comment by Aldrog** [comment]
This issue is related to GStreamer 0.10 as you can see the same picture when launching `gst-launch-0.10 playbin2 uri="direct_uri_to_twitch_stream"` on a regular PC.
You can notice a new branch "gstreamer-1.0" in the repository which development is already completed. The TwitchTube update will roll out as soon as GStreamer 1.0 itself is fully available in Sailfish OS.

UPD: Well, it seems that development of this branch was not actually needed because Jolla says QtMultimedia is going to switch to GStreamer 1.x at the same time as it's added to Sailfish.

**Comment by Aldrog** [comment]
Hi @raikirii, @Termitebug, @ahjolinna,
The yesterday's early access 1.1.9 update for Sailfish OS brought some interesting changes regarding TwitchTube. Particularly, these ones: `Platform upgrade to using a new camera and media stack based on GStreamer 1.x` and `[qtmultimedia] Update to 5.5.0beta1 plus patches. Contributes to JB#17319`. QtMultimedia 5.5 is the one which gained GStreamer 1.x support so I hope switching QtMultimedia version should make a switch to GStreamer 1.0 which in its turn should fix this issue. 

If you've updated, could you please download a testing release and check if the issue has gone?
https://github.com/Aldrog/TwitchTube/releases/tag/v1.0.0-alpha.1

**Comment by raikirii** [comment]
Hey Aldrog. It works great! :D watched 15 minutes with no hiccups. Your app will be my main twitch client. Great work! I will use it in the coming weeks and will report if I find any issues. But so far it works flawlessly. Will it work on the tablet, too?

**Comment by Aldrog** [comment]
@raikirii nice to hear such great news! :smile: 
The app should work on tablet too, but since the APIs for multiple screen sizes are not available yet it's going to simply resize everything to fit into the screen which is not the best solution.

There's also an issue with chat (Twitch decided to change the way they send info about message senders, that's why badges and nick colors stopped working). Now this issue becomes the only blocker for TwitchTube 1.0 release, but I'm too busy at university to fix it. However, I'm going to get some free time next week so you can expect it to be fixed soon enough.

**Comment by Termitebug** [comment]
Second.

Hi Aldrog.
Testing a day late. Just today during a 3D-model study I read RC SW update was released (hyped). So I fired up old and new TwitchTube client (1.9). Indeed the SW update solved the stream problem. 0.9 and 0.2.1-2 versions works flawlessly with very minor problem.

The app has a screen turnoff problem as if you don't tap the screen periodically. Will go blank if left unattended. Otherwise no things to note about than many many thanks for supporting Sailfish OS =). Would flatter this 100%. 

No hurry about the chat.
I would rather suggest to investigate & hotfix first the ”screen off timer” to be forced on / ignored.

Cheers.

**Comment by Aldrog** [comment]
Hi @Termitebug,
Interesting to know video works flawlessly with QtMultimedia 5.0 too.

I've actually added disabling of screen blanking in commit fe3afc05676c7697eeaaa1c358c1c3b9ce26d1b8 which belongs to 0.90, but there's no way for me to check if it worked. Maybe I found some obsolete solution that doesn't work anymore. I will investigate it.

This issue can now be closed I assume, since there're 3 confirmations it no longer presents (two here, one on openrepos).

**Comment by Aldrog** [comment]
And huge thanks to you both @raikirii and @Termitebug for your help and for the positive comments on my app :D

**Comment by Aldrog** [comment]
@Termitebug could you check if screen actually blanks while watching stream in TwitchTube 0.90?
I'm going to open an issue if it does, but I'm not sure as you said you tried both 0.90 and 0.2 (which simply didn't have this feature), the code seems correct and the same solution is used in SailKino app (https://github.com/skvark/SailKino) and even Jolla Gallery seems to make the same dbus call to control screen blanking.
